-- Create table for custom page sections
create table if not exists public.page_sections (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now() not null,
  page text not null check (page in ('home','office','contact')),
  anchor_key text not null,
  sort integer default 0,
  active boolean default true,
  -- i18n fields
  title_ua text,
  title_ru text,
  body_ua text,
  body_ru text,
  -- media
  media_url text,
  media_type text default 'none' check (media_type in ('none','image','video')),
  -- button
  button_text_ua text,
  button_text_ru text,
  button_url text,
  -- styling
  bg_color text default '#ffffff',
  text_color text default '#111827',
  accent_color text default '#361c0c',
  layout text default 'text-left' check (layout in ('text-left','text-right','center')),
  full_width boolean default false
);

create index if not exists idx_page_sections_page on public.page_sections(page);
create index if not exists idx_page_sections_anchor on public.page_sections(page, anchor_key);
create index if not exists idx_page_sections_sort on public.page_sections(page, anchor_key, sort);
