-- Create table for filter options (origins and roasts)
create table if not exists public.filter_options (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now() not null,
  filter_type text not null check (filter_type in ('origin', 'roast')),
  value text not null,
  value_ru text, -- Russian translation
  sort integer default 0,
  active boolean default true,
  unique (filter_type, value)
);

create index if not exists idx_filter_options_type on public.filter_options(filter_type);
create index if not exists idx_filter_options_active on public.filter_options(active);
create index if not exists idx_filter_options_sort on public.filter_options(filter_type, sort);

-- Add value_ru column if it doesn't exist (for existing tables)
alter table public.filter_options add column if not exists value_ru text;

-- Insert default origins with UA and RU translations
insert into public.filter_options (filter_type, value, value_ru, sort, active) values
('origin', 'Колумбія', 'Колумбия', 1, true),
('origin', 'Ефіопія', 'Эфиопия', 2, true),
('origin', 'Бразилія', 'Бразилия', 3, true),
('origin', 'Кенія', 'Кения', 4, true),
('origin', 'Гватемала', 'Гватемала', 5, true),
('origin', 'Ямайка', 'Ямайка', 6, true),
('origin', 'Перу', 'Перу', 7, true),
('origin', 'Коста-Рика', 'Коста-Рика', 8, true),
('origin', 'Індонезія', 'Индонезия', 9, true),
('origin', 'Гаваї', 'Гавайи', 10, true),
('origin', 'Сальвадор', 'Сальвадор', 11, true),
('origin', 'Нікарагуа', 'Никарагуа', 12, true),
('origin', 'Гондурас', 'Гондурас', 13, true),
('origin', 'Панама', 'Панама', 14, true),
('origin', 'Венесуела', 'Венесуэла', 15, true),
('origin', 'Мексика', 'Мексика', 16, true),
('origin', 'Танзанія', 'Танзания', 17, true),
('origin', 'Руанда', 'Руанда', 18, true),
('origin', 'Уганда', 'Уганда', 19, true),
('origin', 'Бурунді', 'Бурунди', 20, true)
on conflict do nothing;

-- Insert default roasts with UA and RU translations
insert into public.filter_options (filter_type, value, value_ru, sort, active) values
('roast', 'Світле', 'Светлое', 1, true),
('roast', 'Середньосвітле', 'Среднесветлое', 2, true),
('roast', 'Середнє', 'Среднее', 3, true),
('roast', 'Середньотемне', 'Среднетемное', 4, true),
('roast', 'Темне', 'Темное', 5, true),
('roast', 'Дуже темне', 'Очень темное', 6, true)
on conflict do nothing;

